#!/bin/sh

alias ls='ls --color=auto --almost-all'
alias grep='grep --color=auto'
alias n='nvim'
z() { zathura --fork "$@" 2>/dev/null }
gccfh() { gcc -fdiagnostics-color=always -g -std=c99 -Wall -Wextra -pedantic -Wno-unused-parameter "$1" -o "${1::-2}" }
